version: '3.3'

services:
  tetris-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tetris-production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - tetris-network

networks:
  tetris-network:
    driver: bridge